global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/f0cc4599-83a5-4da0-b32a-b272394ccd1b'
          send_resolved:  false